### ISSUE TITLE
user is allowed to go to merge page, even when identities consistent

### ISSUE THREAD

**Issue by wikkim** [idbind/identity-binder#11]

**Comment by cberger8** [comment]
For this, should the user just be redirected to say, the accounts page, if the identities are already consistent and there is nothing else to be bound?

**Comment by wikkim** [comment]
Yea, I think that's fine. But it should have some kind of message on the page letting user know that there aren't any accounts to bind.

**Comment by cberger8** [comment]
As of b9389a7e3797159aae1c27d6076d13ea7b018ea7, redirects user to an alert page when trying to access the /bind page if identities are already consistent.
