### ISSUE TITLE
merge page shows all identities on both sides of merge

### ISSUE THREAD

**Issue by wikkim** [idbind/identity-binder#16]

**Comment by wikkim** [comment]
I believe I have the logical identity entities showing on the appropriate sides of the merge page now. But I haven't figured out how to display each account's information in a useful way. I get the results of the picture below when trying to reuse the [account-tile thymeleaf fragment](https://github.com/idbind/identity-binder/blob/master/src/main/resources/templates/fragments/account-tile.html).

![screen shot 2015-03-13 at 4 50 34 pm](https://cloud.githubusercontent.com/assets/4612813/6647060/413192ea-c9a1-11e4-9fd5-a187ccc45561.png)

@jricher Any quick fixes that you can see via an eyeball test of what I have here? [Here is the merge page thymeleaf template](https://github.com/idbind/identity-binder/blob/master/src/main/resources/templates/merge.html)

**Comment by jricher** [comment]
Looks like you're not using the thymeleaf expressions properly, which is causing them to not get interpreted. As I recall, those need to be turned on in the templates for it to do the interpretation.

**Comment by wikkim** [comment]
Oh yup, looks like I needed to turn on Thymeleaf "text inlining".
http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#inlining

Thanks @jricher for the pointer.
