### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by tmlewis** [idbind/identity-binder#19]
Attempted to build  identity-binder after cloning from github.  Built and installed the openID packaged that are required and then ran the command "mvn clean package"  which generated the following output:

[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /Users/tmlewis/Documents/IDbinder/identity-binder/src/main/java/org/mitre/openid/connect/binder/authentication/MultipleIdentityAuthentication.java: Some input files use unchecked or unsafe operations.
[WARNING] /Users/tmlewis/Documents/IDbinder/identity-binder/src/main/java/org/mitre/openid/connect/binder/authentication/MultipleIdentityAuthentication.java: Recompile with -Xlint:unchecked for details.
[INFO] 2 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/tmlewis/Documents/IDbinder/identity-binder/src/main/java/org/mitre/openid/connect/binder/config/WebSecurityConfiguration.java:[7,41] cannot find symbol
  symbol:   class DefaultJwtSigningAndValidationService
  location: package org.mitre.jwt.signer.service.impl
[ERROR] /Users/tmlewis/Documents/IDbinder/identity-binder/src/main/java/org/mitre/openid/connect/binder/config/WebSecurityConfiguration.java:[179,16] cannot find symbol
  symbol:   class DefaultJwtSigningAndValidationService
  location: class org.mitre.openid.connect.binder.config.WebSecurityConfiguration
[ERROR] /Users/tmlewis/Documents/IDbinder/identity-binder/src/main/java/org/mitre/openid/connect/binder/config/WebSecurityConfiguration.java:[183,17] cannot find symbol
  symbol:   class DefaultJwtSigningAndValidationService
  location: class org.mitre.openid.connect.binder.config.WebSecurityConfiguration
[ERROR] /Users/tmlewis/Documents/IDbinder/identity-binder/src/main/java/org/mitre/openid/connect/binder/config/WebSecurityConfiguration.java:[183,75] cannot find symbol
  symbol:   class DefaultJwtSigningAndValidationService
  location: class org.mitre.openid.connect.binder.config.WebSecurityConfiguration
[INFO] 4 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.809 s
[INFO] Finished at: 2015-02-27T18:19:43-05:00
[INFO] Final Memory: 25M/226M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project identity-binder: Compilation failure: Compilation failure:
[ERROR] /Users/tmlewis/Documents/IDbinder/identity-binder/src/main/java/org/mitre/openid/connect/binder/config/WebSecurityConfiguration.java:[7,41] cannot find symbol
[ERROR] symbol:   class DefaultJwtSigningAndValidationService
[ERROR] location: package org.mitre.jwt.signer.service.impl
[ERROR] /Users/tmlewis/Documents/IDbinder/identity-binder/src/main/java/org/mitre/openid/connect/binder/config/WebSecurityConfiguration.java:[179,16] cannot find symbol
[ERROR] symbol:   class DefaultJwtSigningAndValidationService
[ERROR] location: class org.mitre.openid.connect.binder.config.WebSecurityConfiguration
[ERROR] /Users/tmlewis/Documents/IDbinder/identity-binder/src/main/java/org/mitre/openid/connect/binder/config/WebSecurityConfiguration.java:[183,17] cannot find symbol
[ERROR] symbol:   class DefaultJwtSigningAndValidationService
[ERROR] location: class org.mitre.openid.connect.binder.config.WebSecurityConfiguration
[ERROR] /Users/tmlewis/Documents/IDbinder/identity-binder/src/main/java/org/mitre/openid/connect/binder/config/WebSecurityConfiguration.java:[183,75] cannot find symbol
[ERROR] symbol:   class DefaultJwtSigningAndValidationService
[ERROR] location: class org.mitre.openid.connect.binder.config.WebSecurityConfiguration
[ERROR] -> [Help 1]

**Comment by wikkim** [comment]
Discovered cause of this issue was my code being out-of-date with the latest snapshot of mitreid-connect. Apparently the class causing this issue was renamed for consistency in the upstream project.
DefaultJwtSigningAndValidationService -> DefaultJWTSigningAndValidationService
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/529

**Comment by wikkim** [comment]
Addressed by commit 2706a0b9694ef30791eca2e6d85b0005301edc58
