### ISSUE TITLE
Type mismatch: cannot convert from NamedAdminAuthoritiesMapper to GrantedAuthoritiesMapper

### ISSUE THREAD

**Issue by cberger8** [idbind/identity-binder#29]

**Comment by wikkim** [comment]
Change in upstream project:
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/commit/d1e8529a7b23bb07e8d1d17613b0d2350a72e185#diff-3026f688f0aeddf901ec8de19952ff28L40

Example of using new method signatures:
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/286d433da6fc1425974fc79831bf159abd3a57ff/openid-connect-client/src/main/java/org/mitre/openid/connect/client/OIDCAuthenticationProvider.java#L68-84

**Comment by wikkim** [comment]
resolved by 70f5b58c56a6eef93a40b21b11802a5f7a9c246d
