### ISSUE TITLE
implement basic logging

### ISSUE THREAD

**Issue by wikkim** [idbind/identity-binder#36]
for login events, binding events, errors, etc..

**Comment by wikkim** [comment]
using logging framework like sl4j or log4j

**Comment by wikkim** [comment]
need to log:
1. any user-initiated actions (logins, bindings, unbindings)
2. query attempts on the query API, logging both successful and unsuccessful attempts
3. errors, exceptions, all the hypothetical "else"s (most marked with TODOs) to indicate something went wrong

**Comment by cberger8** [comment]
Via Spring docs: "By default, If you use the ‘Starter POMs’, Logback will be used for logging" [see https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html] -- as this is the case, looks like it should be pretty trivial to implement logging with no further dependency setup.

**Comment by wikkim** [comment]
lets set up some of the logging config to have some kind of reasonable rolling/appending logging that saves off the log files on a daily basis with datestamps in the filename. After verifying that works, comment that config and make new config for just logging to console, so that this project will only print to console by default out of the box, but with the option for file-saved logs.

**Comment by wikkim** [comment]
framework is in place now. probably need to sprinkle in more logging statements as needed, but considering this issue closed now.
