### ISSUE TITLE
bind/unbind API naming

### ISSUE THREAD

**Issue by cberger8** [idbind/identity-binder#59]
Didn't like when I used "/bind" and "/unbind" as values for the mappings in BindAPIController since they were already used in BinderController, so renamed them to "/api-bind" and "/api-unbind". Might want to rename these.

**Comment by wikkim** [comment]
let's go with /api/bind and /api/unbind

**Comment by cberger8** [comment]
Resolved by b6535c3cf70a14c4e8d6245bb15231445fc77189
